services:
  db:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feast
    image: mariadb:11.8
    volumes:
      - souschef_data:/var/lib/mysql
    networks:
      - backend
    platform: linux/amd64

  web:
    restart: always
    build: .
    volumes:
      - ./:/code
      # in order to debug django you may mount your site-packages directory
      # - ./env/lib/python3.9/site-packages/django://usr/local/lib/python3.7/site-packages/django
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    platform: linux/amd64

volumes:
  souschef_data:

networks:
  backend:
